spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: eclp
    password: eclp
    # explain the jikari
    # http://blog.csdn.net/clementad/article/details/46928621
    hikari:
      #一个 连接的生命时长（毫秒），超时而且没被使用则被释放（retired）,缺省：30分钟，建议设置比数据库超市市场少30秒以上
      maxLifetime: 1765000
      #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maxmumPoolSize: 15
      pool-name: bosPoolName
      connection-test-query: select 1 from dual
      minimum-idle: 3

    secondary:
      driver-class-name: com.mysql.jdbc.Driver
      username: eclp
      password: eclp
      # explain the jikari
      # http://blog.csdn.net/clementad/article/details/46928621
      hikari:
        #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired）,缺省：30分钟，建议设置比数据库超市市场少30秒以上
        maxLifetime: 1765000
        #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
        maxmumPoolSize: 15
        pool-name: bosPoolName
        connection-test-query: select 1 from dual
        minimum-idle: 3

mybatis:
  mapperLocations: classpath:mapper/*.xml

---
#开发环境配置
spring:
  profiles : dev
  datasource:
    url: jdbc:mysql://192.168.159.38:3306/

---
#测试环境配置
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://192.168.159.38:3306/

---
#生产环境配置
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.159.38:3306/
